myblog/myblog/apps/articles/urls.py
from django.urls import path
from .import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    ]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

myblog/myblog/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('Название стратьи', max_length=50)
    article_text = models.TextField('Текст статьи', max_length=1000)
    pud_date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):  #была ли данная статься опубликована недавно*
        return self.pud_date >= (timezone.now()-datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)  # Привязка комментария к статье
    author_name = models.CharField('Имя автора', max_length=50)
    comment_text = models.CharField("Текст комментария ", max_length=100)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

myblog/myblog/apps/articles/views.py
from django.urls import reverse
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Article


def index(request):
    latest_articles_list = Article.objects.order_by('-pud_date')[:5]  # Выведет список последних 5 статей
    return render(request, 'articles/list.html',
                  {'latest_articles_list': latest_articles_list})  # передаем в шаблон


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена")

    latest_comments_list =a.comment_set.order_by('-id')[:10]#Возварщаем список комментов последние 10
    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list':latest_comments_list})#Возвращаем список статей



def leave_comment(request, article_id):  #Оставление комментариев
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена")

    a.comment_set.create(author_name=request.POST['name'],
                         comment_text=request.POST['text'])
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))  #возвращение на траницу при  обновлении после написания комментария

myblog/myblog/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock%}

{% block content%}

<h2>{{article.article_title}}</h2>
<p>{{article.article_text}}</p>
<em>{{article.pud_date}}</em>

<!--Используем метод из шаблонизатора -->
{%if article.was_published_recently%}
Новая статья!
{%endif%}
<hr>
{% if latest_comments_list%}
    {%for c in latest_comments_list%}
        <p>
            <strong>{{c.author_name}}
                <p>{{c.comment_text}}</p></strong>
        </p>
    {%endfor%}

{%else%}
Комментарии не найдены! Станьте первым ;)
{% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

    {%csrf_token%}<!-- защита от CSRF отак. по умолчанию должна быть -->

    <input type="text" required placeholder="Ваше имя" name="name" ><br>
    <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>

    <button type="submit">Оставить комментарий</button>
</form>

{% endblock %}

myblog/myblog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} {{articles.articles_title}} {% endblock%}

{% block content%}

    {% if latest_articles_list %} <!-- работа с шаблонизатором -->

        {% for a in latest_articles_list%}
            <a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
        {% endfor%}

        {%else%}
            Статьи не найдены )=
        {% endif%}

{% endblock %}

myblog/myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{%endblock%}</title>
</head>
<body>
    {% block content %} {% endblock %}

</body>
</html>